##
# Build container for CI environment
##
version: '2.1'

services:
  base:
    build:
      context: .
      dockerfile: Dockerfile.build
    volumes:
      - ..:/var/www
    environment:
      GIT_USER_EMAIL: "GitLab"
      GIT_USER_NAME: "gitlab@phase2technology.com"
      CI_COMMIT_HASH: "${CI_BUILD_REF}"
      CI_BRANCH: "${CI_BUILD_REF_NAME}"
      NVM_DIR: /home/docker/.nvm
    env_file:
      # Pass project-specific environment variables into cli container.
      - ../.env
