---
# Source: chart/charts/mariadb/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: release-name-mariadb
  labels:
    app: release-name-mariadb
    chart: mariadb-2.1.8
    release: "release-name"
    heritage: "Tiller"
data:
  my.cnf: |-