---
# Source: chart/charts/mariadb/templates/deployment.yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: release-name-mariadb
  labels:
    app: release-name-mariadb
    chart: mariadb-2.1.8
    release: "release-name"
    heritage: "Tiller"
spec:
  template:
    metadata:
      labels:
        app: release-name-mariadb
    spec:
      securityContext:
        runAsUser: 1001
        fsGroup: 1001
      initContainers:
      - name: "copy-custom-config"
        image: "busybox"
        imagePullPolicy: "IfNotPresent"
        command: ["sh", "-c", "mkdir -p /bitnami/mariadb/conf && cp /bitnami/mariadb_config/my.cnf /bitnami/mariadb/conf/my_custom.cnf"]
        volumeMounts:
        - name: config
          mountPath: /bitnami/mariadb_config
        - name: data
          mountPath: /bitnami/mariadb
      containers:
      - name: mariadb
        image: "bitnami/mariadb:10.1.31-r2"
        imagePullPolicy: "IfNotPresent"
        env:
        - name: MARIADB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: release-name-mariadb
              key: mariadb-root-password
        - name: MARIADB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: release-name-mariadb
              key: mariadb-password
        - name: MARIADB_USER
          value: "admin"
        - name: MARIADB_DATABASE
          value: "drupal_octane"
        ports:
        - name: mysql
          containerPort: 3306
        livenessProbe:
          exec:
            command:
            - mysqladmin
            - ping
          initialDelaySeconds: 30
          timeoutSeconds: 5
        readinessProbe:
          exec:
            command:
            - mysqladmin
            - ping
          initialDelaySeconds: 5
          timeoutSeconds: 1
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          
        volumeMounts:
        - name: data
          mountPath: /bitnami/mariadb
      volumes:
      - name: config
        configMap:
          name: release-name-mariadb
      - name: data
        persistentVolumeClaim:
          claimName: release-name-mariadb