---
# Source: chart/charts/mariadb/templates/pvc.yaml

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: release-name-mariadb
  labels:
    app: release-name-mariadb
    chart: mariadb-2.1.8
    release: "release-name"
    heritage: "Tiller"
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "1Gi"
