---
# Source: chart/charts/mariadb/templates/svc.yaml
apiVersion: v1
kind: Service
metadata:
  name: release-name-mariadb
  labels:
    app: release-name-mariadb
    chart: mariadb-2.1.8
    release: "release-name"
    heritage: "Tiller"
  annotations:
spec:
  type: ClusterIP
  ports:
  - name: mysql
    port: 3306
    targetPort: mysql
  selector:
    app: release-name-mariadb
