apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "chart.fullname" . }}
  labels:
    app: {{ template "chart.name" . }}
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    heritage: {{ .Release.Service }}
    webcontainer: "true"
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ template "chart.name" . }}
        release: {{ .Release.Name }}
        webcontainer: "true"
    spec:
      containers:
        - name: {{ template "chart.fullname" . }}-build
          image: "{{ .Values.image.build }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
            - name: webroot
              mountPath: /var/www
        - name: {{ template "chart.fullname" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          - name: BUILD_ID
            value: {{ default "build-0" .Values.build_id | quote }}
          - name: DOCROOT
            value: {{ default "" .Values.env.docroot | quote }}
          - name: PROJECT_TIER
            value: {{ default "" .Values.env.tier | quote }}
          - name: PHP_MAX_EXECUTION_TIME
            value: {{ default "60" .Values.env.phpMaxExecutionTime | quote }}
          - name: PHP_MEMORY_LIMIT
            value: {{ default "256m" .Values.env.phpMemoryLimit | quote }}
          - name: MEMCACHED_HOST
            value: {{ template "chart.memcached.fullname" . }}
          - name: MYSQL_HOST
            value: {{ template "chart.mariadb.fullname" . }}
          - name: MYSQL_PORT
            value: "3306"
          - name: MYSQL_USER
            value: {{ default "" .Values.mariadb.mariadbUser | quote }}
          - name: MYSQL_DATABASE
            value: {{ default "" .Values.mariadb.mariadbDatabase | quote }}
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ template "chart.mariadb.fullname" . }}
                key: mariadb-password
          ports:
            - name: {{ .Values.service.name }}
              containerPort: {{ .Values.service.internalPort }}
          volumeMounts:
            #- name: {{ default "cms" .Values.ingress.url.project }}-files
            #  mountPath: {{ .Values.volumeMounts.cmsfiles.mountPath }}
            - name: webroot
              mountPath: /var/www
          # TODO these probes were /user/login, determine what they should be
          # TODO the timeoutSeconds were bumped higher than swarm test project
          #      to support the web container not being cycled during cache
          #      rebuilds or other things where Drupal takes a bit to become
          #      responsive again
          livenessProbe:
            timeoutSeconds: 10
            httpGet:
              path: /robots.txt
              port: {{ .Values.service.internalPort }}
          readinessProbe:
            timeoutSeconds: 10
            httpGet:
              path: /robots.txt
              port: {{ .Values.service.internalPort }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
      imagePullSecrets:
        - name: gitlab-registry-secret
      initContainers:
        - name: webdata
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          command: [bash, -c]
          args: ["cp -r /var/www/* /data"]
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
            - name: webroot
              mountPath: /data
      volumes:
        - name: {{ default "cms" .Values.ingress.url.project }}-files
        {{- if .Values.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.cmsfiles.existingClaim | default (printf "%s-files" (include "chart.fullname" .)) }}
        {{- else }}
          emptyDir: {}
        {{- end }}
        - name: webroot
          emptyDir: {}
    {{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
    {{- end }}
